# Requires Windows PowerShell 5.1 or PowerShell 7. No downloads or Docker calls.
# Creates course folders and per-PC dashboard credentials. Existing files stay intact.
[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot

foreach ($relative in @('compose.yaml', 'inputs/input_marker.txt', 'course-tools/check_environment.py')) {
    if (-not (Test-Path -LiteralPath (Join-Path $PSScriptRoot $relative) -PathType Leaf)) {
        throw "Package file missing: $relative. Extract the whole ZIP before continuing."
    }
}

foreach ($relative in @('workspace', 'workspace/evidence/lesson02', 'workspace/outputs', 'workspace/context', 'workspace/tests', 'workspace/notes', 'workspace/baseline')) {
    New-Item -ItemType Directory -Force -Path (Join-Path $PSScriptRoot $relative) | Out-Null
}

function New-RandomHex([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return ([BitConverter]::ToString($bytes)).Replace('-', '').ToLowerInvariant()
}

$envPath = Join-Path $PSScriptRoot '.env'
if (-not (Test-Path -LiteralPath $envPath)) {
    $password = New-RandomHex 12
    $secret = New-RandomHex 32
    $lines = @('DASHBOARD_PORT=9119', 'DASHBOARD_USERNAME=student', "DASHBOARD_PASSWORD=$password", "DASHBOARD_SECRET=$secret")
    [System.IO.File]::WriteAllText($envPath, ($lines -join "`n") + "`n", [System.Text.Encoding]::ASCII)
    Write-Host 'Created personal dashboard credentials in .env.'
} else {
    Write-Host 'Existing .env preserved. No credentials changed.'
}

$settings = @{}
foreach ($line in [System.IO.File]::ReadAllLines($envPath)) {
    if ($line -match '^(DASHBOARD_PORT|DASHBOARD_USERNAME|DASHBOARD_PASSWORD|DASHBOARD_SECRET)=(.*)$') {
        if ($settings.ContainsKey($Matches[1])) { throw "Duplicate setting: $($Matches[1])" }
        $settings[$Matches[1]] = $Matches[2].Trim()
    }
}
foreach ($key in @('DASHBOARD_PORT','DASHBOARD_USERNAME','DASHBOARD_PASSWORD','DASHBOARD_SECRET')) {
    if (-not $settings.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($settings[$key])) {
        throw "Missing setting: $key. Existing .env was not overwritten."
    }
}
if ($settings['DASHBOARD_PASSWORD'] -notmatch '^[0-9a-f]{24}$' -or $settings['DASHBOARD_SECRET'] -notmatch '^[0-9a-f]{64}$') {
    throw 'Expected credentials generated by this course helper. Do not use the placeholders in .env.example.'
}
if ($settings['DASHBOARD_USERNAME'] -notmatch '^[A-Za-z0-9_-]+$') { throw 'Invalid dashboard username.' }
$port = 0
if (-not [int]::TryParse($settings['DASHBOARD_PORT'], [ref]$port) -or $port -lt 1024 -or $port -gt 65535) {
    throw 'DASHBOARD_PORT must be an integer from 1024 through 65535.'
}

$marker = Join-Path $PSScriptRoot 'workspace/evidence/lesson02/host_marker.txt'
if (-not (Test-Path -LiteralPath $marker)) {
    [System.IO.File]::WriteAllText($marker, "created-on-windows`n", [System.Text.Encoding]::ASCII)
}
Write-Host 'Folders ready. Existing work preserved.'
Write-Host ("Dashboard URL : http://127.0.0.1:{0}" -f $port)
Write-Host ("Username      : {0}" -f $settings['DASHBOARD_USERNAME'])
Write-Host ("Password      : {0}" -f $settings['DASHBOARD_PASSWORD'])
Write-Host 'Keep the password private. The signing secret is not printed.'
